// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChatHeader: typeof import('./src/components/chat/chatHeader/index.vue')['default']
    ChatMessage: typeof import('./src/components/chat/chatMessage/index.vue')['default']
    ChatPop: typeof import('./src/components/chatPop/index.vue')['default']
    ChatTool: typeof import('./src/components/chat/chatTool/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    GlobalCfg: typeof import('./src/components/globalCfg/index.vue')['default']
    MessageArea: typeof import('./src/components/chat/messageArea/index.vue')['default']
    MusicLyric: typeof import('./src/components/chat/musicLyric/index.vue')['default']
    MusicPlayer: typeof import('./src/components/chat/musicPlayer/index.vue')['default']
    MusicProgress: typeof import('./src/components/chat/musicProgress/index.vue')['default']
    OnlineUserList: typeof import('./src/components/chat/chatHeader/components/OnlineUserList.vue')['default']
    PersonInfo: typeof import('./src/components/chat/chatHeader/components/PersonInfo.vue')['default']
    RoomConfig: typeof import('./src/components/chat/chatHeader/components/RoomConfig.vue')['default']
    RoomList: typeof import('./src/components/chat/chatHeader/components/RoomList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    ToolChooseMusic: typeof import('./src/components/chat/chatTool/components/ToolChooseMusic.vue')['default']
    ToolCollect: typeof import('./src/components/chat/chatTool/components/ToolCollect.vue')['default']
    ToolQueueList: typeof import('./src/components/chat/chatTool/components/ToolQueueList.vue')['default']
    VolumeSlider: typeof import('./src/components/chat/musicLyric/volumeSlider.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
